//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   WITH SL (組織CD, 上位組織CD, 組織階層区分) AS
        ///(SELECT 組織CD, 上位組織CD, 組織階層区分 FROM CMSM組織 WHERE 組織CD = @1
        ///UNION ALL
        ///SELECT A.組織CD, A.上位組織CD, A.組織階層区分 FROM CMSM組織 A
        ///  JOIN SL ON SL.上位組織CD = A.組織CD AND SL.組織階層区分 != &apos;1&apos;)
        ///SELECT DISTINCT メニューID, 画面名, FIRST_VALUE(許否フラグ)
        ///  OVER (PARTITION BY メニューID ORDER BY 許否フラグ DESC) 許否フラグ
        ///  FROM (SELECT DISTINCT M.メニューID, 画面名, ロールID, FIRST_VALUE(許否フラグ)
        ///  OVER (PARTITION BY M.メニューID, R.ロールID ORDER BY SL.組織階層区分 DESC) 許否フラグ
        ///  FROM CMSMメニュー M
        ///  LEFT JOIN CMSMメニュー管理 R ON R.ロールID IN (SEL [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMSMメニューレベル1 {
            get {
                return ResourceManager.GetString("CMSMメニューレベル1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WITH SL (組織CD, 上位組織CD, 組織階層区分) AS
        ///(SELECT 組織CD, 上位組織CD, 組織階層区分 FROM CMSM組織 WHERE 組織CD = @1
        ///UNION ALL
        ///SELECT A.組織CD, A.上位組織CD, A.組織階層区分 FROM CMSM組織 A
        ///  JOIN SL ON SL.上位組織CD = A.組織CD AND SL.組織階層区分 != &apos;1&apos;)
        ///SELECT DISTINCT メニューID, 画面名, URL, オプション, FIRST_VALUE(許否フラグ)
        ///  OVER (PARTITION BY メニューID ORDER BY 許否フラグ DESC) 許否フラグ
        ///  FROM (SELECT DISTINCT M.メニューID, 画面名, URL, オプション, ロールID, FIRST_VALUE(許否フラグ)
        ///  OVER (PARTITION BY M.メニューID, R.ロールID ORDER BY SL.組織階層区分 DESC) 許否フラグ
        ///  FROM CMSMメニュー M
        ///  LEFT JOIN CMSMメニュ [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMSMメニューレベル2 {
            get {
                return ResourceManager.GetString("CMSMメニューレベル2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT
        ///A.基準値CD,
        ///A.基準値名,
        ///A.文字項目1
        ///-- [ROWNUMBER]
        ///FROM CMSM汎用基準値 A
        ///-- WHERE [検索条件]
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMSM汎用基準値 {
            get {
                return ResourceManager.GetString("CMSM汎用基準値", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT
        ///A.組織CD,
        ///A.組織名,
        ///A.組織階層区分,
        ///H1.基準値名 組織階層区分名,
        ///A.上位組織CD,
        ///S2.組織名 上位組織名
        ///-- [共通項目]
        ///FROM CMSM組織 A
        ///LEFT JOIN CMSM汎用基準値 H1 ON H1.分類CD = &apos;M001&apos; AND H1.基準値CD = A.組織階層区分
        ///LEFT JOIN CMSM組織 S2 ON S2.組織CD = A.上位組織CD
        ///-- [共通JOIN]
        ///-- WHERE [検索条件]
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMSM組織 {
            get {
                return ResourceManager.GetString("CMSM組織", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT 
        ///U.ユーザID Id,
        ///U.ユーザ名 Name,
        ///&apos;&apos; Roles,
        ///U.組織CD SoshikiCd,
        ///S1.組織名 SoshikiName,
        ///S1.組織階層区分 SoshikiKaisoKbn
        ///FROM CMSMユーザ U 
        ///JOIN CMSM組織 S1 ON S1.組織CD = U.組織CD 
        ///WHERE U.ユーザID = {0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
    }
}
